bump playwright to 1.52.0

diff --git a/ubuntu-22/Dockerfile b/ubuntu-22/Dockerfile
--- a/ubuntu-22/Dockerfile
+++ b/ubuntu-22/Dockerfile
@@ -1,19 +1,11 @@
 ARG PLAYWRIGHT_VERSION
 FROM mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-jammy
 
-# RUN set -ex; \
-# 	apt-get update; \
-# 	DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
-# 		npm \
-# 		; \
-# 	apt-get clean; \
-# 	rm -rf /var/lib/apt/lists/*
-
 # Essentials for scripts
 ENV NODE_PATH=/usr/lib/node_modules
 RUN set -e; \
 	if [ "$NODE_PATH" != "$(npm root -g)" ]; then \
-		echo >&2 "NODE_PATH invalid" && exit 2; \
+		echo >&2 "Invalid \$NODE_PATH: $NODE_PATH" && exit 2; \
 	fi
 
 RUN set -e; \
